export const paths = {
  common: {
    privacyPolicy: '/privacy-policy',
    termsOfService: '/terms-of-service',
    onlineCustomerService: 'https://t.me/Ubbet_Officalbot',
  },
  home: '/',
  live: '/live',
  sport: '/sport',
  lottery: '/lottery',
  electronic: '/electronic',
  login: '/login',
  signup: '/signup',
  promotions: {
    root: '/promotions',
    allPromotions: '/promotions/all-promotions',
    limitedTimeEvent: '/promotions/limited-time-events',
    newUserFirstDeposit: '/promotions/first-deposit-for-new-users',
  },
  auth: {
    login: '/login',
    signup: '/signup',
    forgotPassword: '/forgot-password',
  },
  dashboard: {
    root: '/dashboard',
    cashIn: '/dashboard/cash-in',
    transferPoint: '/dashboard/transfer-point',
    cashOut: '/dashboard/cash-out',
    personalProfile: '/dashboard/personal-profile',
    vipPrivileges: '/dashboard/vip-privileges',
    myWallet: '/dashboard/my-wallet',
    transactionHistory: '/dashboard/transaction-history',
    bettingHistory: '/dashboard/betting-history',
    welfareCenter: '/dashboard/welfare-center',
    messageCenter: '/dashboard/message-center',
  },
  footer: {
    root: '/footer',
    FAQ: '/footer/FAQ',
    PrivacyPolicy: '/footer/PrivacyPolicy',
    TermsOfService: '/footer/TermsOfService',
    Disclaimer: '/footer/Disclaimer',
    AboutUs: '/footer/AboutUs',
    ContactUs: '/footer/ContactUs',
    Deposit: '/footer/Deposit',
    Promotions: '/footer/Promotions',
  },
}
